spring:    
    application:        
        name:  todo-app
    datasource:        
        driver-class-name: org.h2.Driver
        username: a
        password: a 
        url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE"
    h2:
      console:
          path: /h2-console
          enabled: true
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
          ddl-auto: create-drop
    springfox:
      documentation:
        swagger-ui:
          base-url: todoapp
    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method
        disable-swagger-default-url: true
        use-root-path: true
    packages-to-scan: com.aldadev1.todoapp.controller