spring:
    application:
      name:todo-app
    datasource:
      driver-class-name:org.h2.driver
      username:a
      password:a
      url:"jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT_FALSE"
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
          ddl-auto: create-drop 
    h2:
      console:
          path: /h2-console
          enabled: true
          

                
